### ISSUE TITLE
the route-reflector error"Network not in table"

### ISSUE THREAD

**Issue by candiLin** [osrg/gobgp#1493]
Hi, I build the bgp environment of three hosts "192.168.162.131, 192.168.162.132, 192.168.162.134"
and use the host "192.168.162.131" as the Route Reflector. 
the setting of three hosts is below:
host "192.168.162.131":

[global.config]
  as = 65001
  router-id = "192.168.162.131"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.162.134"
    peer-as = 65001

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.162.132"
    peer-as = 65001

host "192.168.162.132":
[global.config]
  as = 65001
  router-id = "192.168.162.132"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.162.134"
    peer-as = 65001

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.162.131"
    peer-as = 65001
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "192.168.162.132"

host "192.168.162.134":

[global.config]
  as = 65001
  router-id = "192.168.162.134"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.162.131"
    peer-as = 65001
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "192.168.162.134"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.162.132"
    peer-as = 65001

I run "gobgp neighbor 192.168.162.131 adj-out" in host "192.168.162.134"
but it shows "Network not in table"
What's going wrong here？

**Comment by fujimoto-s** [comment]
Have you added any route?

Initially, GoBGP has no route because it will not get the kernel routing table if not configured.
You need to add any routes to it or enable its zebra feature.

[Adding routes]
e.g.) `gobgp global rib add 10.33.0.0/16 -a ipv4`
Detail: https://github.com/osrg/gobgp/blob/master/docs/sources/cli-command-syntax.md#--syntax

[Using zebra feature]
See: https://github.com/osrg/gobgp/blob/master/docs/sources/zebra.md

**Comment by candiLin** [comment]
@fujimoto-s  You are right, I don't add any route, thank you!

**Comment by candiLin** [comment]
@fujimoto-s  Can I use the toml file to add the route?

**Comment by fujimoto-s** [comment]
GoBGP does not have such a feature.
You need to add routes after it starts.

However, if you enable the zebra feature, you can install static routes to zebra, and GoBGP will receive the routes when it starts.
Note: zebra will distribute reachable routes only. You need to install reachable routes, otherwise it will not work well.
