### ISSUE TITLE
Compilation breaks

### ISSUE THREAD

**Issue by shadrick** [osrg/gobgp#1547]
Compiler output:
`osrg/gobgp/table/path.go:392:37: multiple-value uuid.NewV4() in single-value context`

If you have your plates full i can suggest in a PR
Thanks, guys

**Comment by ddexterpark** [comment]
I've tried to build a gobgp docker container with both Ubuntu & Alpine both have the same issue:
 
```
/go/src/github.com/osrg/gobgp/table/path.go:392:37: multiple-value uuid.NewV4() in single-value context
The command '/bin/sh -c go get github.com/osrg/gobgp/gobgp' returned a non-zero code: 2
```

Any help would be appreciated, thanks!

**Comment by iwaseyusuke** [comment]
Thanks for your reporting!

This issue seems to be caused from the following commit on `satori/go.uuid`.
This commit changes signature of `uuid.NewV4()` to return two value `(UUID, error)` instead of `UUID`.
https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c

The following fixes this issue?
```go
# osrg/gobgp/table/path.go:

func (path *Path) AssignNewUUID() {
	path.OriginInfo().uuid = uuid.Must(uuid.NewV4())
}
```

**Comment by iwaseyusuke** [comment]
Or, how about using `dep ensure` before your compilation as [README](https://github.com/osrg/gobgp#to-start-developing-gobgp)?

**Comment by fujita** [comment]
As @iwaseyusuke pointed out, please follow the instruction in README
https://github.com/osrg/gobgp#to-start-developing-gobgp
