### ISSUE TITLE
Go Native BGP library broken on master

### ISSUE THREAD

**Issue by ecbaldwin** [osrg/gobgp#1800]
Basically, [this no longer works][1] on master because `config` and `table` are now internal. The `server` package is still available but I cannot call [Start][2] because it requires a config.Global pointer which I cannot create because it is internal. The [AddPath][3] also calls for parameters from an internal module.

I'd still like to be able to embed gobgp, even if I have to use the grpc API to manage it. However, it currently seems impossible on master.

BTW, I was using master because I need multihop BGP.

[1]: https://github.com/osrg/gobgp/blob/3dc23d3075f13f2976afd255ef2fd9b1410acc77/docs/sources/lib.md
[2]: https://github.com/osrg/gobgp/blob/3dc23d3075f13f2976afd255ef2fd9b1410acc77/pkg/server/server.go#L1832
[3]: https://github.com/osrg/gobgp/blob/3dc23d3075f13f2976afd255ef2fd9b1410acc77/pkg/server/server.go#L1758

**Comment by fujita** [comment]
Sorry about that. It should have been a temporary breakage but I took longer than I expected. I updated the APIs except for Watch stuff. 

Now the APIs use structures in api/ instead of config/ and table/.
https://github.com/osrg/gobgp/blob/master/docs/sources/lib.md

I'll comment functions and structures but not yet. Free fee to ask how to use the APIs. Also comments on the APIs are welcome.
