### ISSUE TITLE
AddPath routes have same PathId (same localId).

### ISSUE THREAD

**Issue by kishiguro** [osrg/gobgp#2079]
When we enable AddPath in Route Reflector and reboot AddPath routes originator router at the same time, sometimes AddPath routes have same PathId=1 (actually same local identifier).
When this happens, Route Reflector client replace AddPath routes with latter one.  So there will be missing routes.  We enable long lived graceful restart and legacy graceful restart.  I'm not sure it affects to this issue or not.
My observation is this is due to missing lock of type Destination member `localIdMap`.  When same prefix routes with different nexthop update comes at the same time, there would be situation of assign same PathId to Path.

**Comment by fujita** [comment]
IIRC, only the main goroutine calls localIdMap methods. Am I missing something?

**Comment by kishiguro** [comment]
if so is there any situation local identifier has same value?  I try to find the root cause but no success...

**Comment by kishiguro** [comment]
Do you think is there any situation where explicit or implicit withdraw override existing local path id in case of AddPath?

```
		if newPath.GetSource().Equal(path.GetSource()) && newPath.GetNlri().PathIdentifier() == path.GetNlri().PathIdentifier() {
			log.WithFields(log.Fields{
				"Topic": "Table",
				"Key":   dest.GetNlri().String(),
				"Path":  path,
			}).Debug("Implicit withdrawal of old path, since we have learned new path from the same peer")

			found = i
			newPath.GetNlri().SetPathLocalIdentifier(path.GetNlri().PathLocalIdentifier())
			break
		}
```

**Comment by fujita** [comment]
Can you explain the details of the setup?

1. you have three peers, rr, rr client, another peer advertising a route to rr?
2. you started rr without addpath enabled, then change the configuration of rr to enable addpath and reboot another peer advertising a route to rr?
3. the duplication of local id happens in rr, right?

**Comment by kishiguro** [comment]
Sorry for late reply.

> you have three peers, rr, rr client, another peer advertising a route to rr?

Yes, we have 3 RRs and many RR clients.  Each RR client connect to 3 RRs at the same time.
RR clients advertise one's own routes to 3 RRs then RR reflect the routes to other RR clients.

> you started rr without addpath enabled, then change the configuration of rr to enable addpath and reboot another peer advertising a route to rr?

Yes, at boot time RR does not have any configuration.  We inject configuration from gRPC API.

> the duplication of local id happens in rr, right?

Yes, duplication of local path id happens only in RR never in client side.

**Comment by fujita** [comment]
Let me understand the issue clearly.

The RR doesn't have the two routes with the same local ID. The RR replaces the old route with the new route; both are assigned with the same local ID.

Right?

**Comment by kishiguro** [comment]
Yes, that is correct.

**Comment by fujita** [comment]
I found one bug that causes this situation.
Let's assume that we have one RR and two RR clients (A and B).

1. RR gets one route from client A (local ID 1 is assigned to the route).
2. installing a policy to reject the route to RR then client A is dead.
3. RR starts GR for A; `propagateUpdate()` is called with the route with stale bit. The route is converted to the withdraw route due to the policy.
4. The withdraw route clears the bit for local ID 1 even though the route with local ID 1 exists in the adj-in table.
5. uninstalling the policy.
6. RR gets a new route with the same prefix from client B. Local ID 1 is assigned to the route too.
7. executing softreset or something brings back the route in client A's adj-in to the global rib. then we have two routes with the same Local ID 1.

I think that the route problem is that we clear the bit even when the ID for the bit is still used in adj-in.

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/commit/2682343deac42e6384f915dd5a1cde0154508019

I've pushed a fix for this.

**Comment by kishiguro** [comment]
We've confirmed the issue has been fixed.  Thanks for all of support!
