### ISSUE TITLE
Failed Proto Imports - Python gRPC

### ISSUE THREAD

**Issue by bgianpetro** [osrg/gobgp#2095]
When generating the Python interface as specified in the documentation as follows:

```
python -m grpc_tools.protoc -I./api --python_out=. --grpc_python_out=. api/gobgp.proto api/attribute.proto api/capability.proto
```

I received errors about not being able to find the imports out of the 'gobgp.proto' file, like this:

>gobgp.proto: Import "any/any.proto" was not found or had errors.
>gobgp.proto: Import "empty/empty.proto" was not found or had errors.
>gobgp.proto: Import "timestamp/timestamp.proto" was not found or had errors.

I was able to fix this by modifying the references as follows in the api/*.proto files.

From this:
```
import "any/any.proto";
import "empty/empty.proto";
import "timestamp/timestamp.proto";
```

To this:
```
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
```

I don't know if this is an issue with my Python library location (user-based) or if it is just a general Python thing.  If the fix would work for everything I can submit a PR.

**Comment by fujita** [comment]
https://github.com/osrg/gobgp/blob/master/tools/grpc/genproto.sh#L32
You need to specify another include path like the above.

**Comment by gustavooferreira** [comment]
Had exactly the same issue in python and finally managed to solve it.
Was going to open an issue but then realized there was one opened (and closed) already.

Including the path is not enough, at least not for python.

It will generate the files but python code won't work because of the wrong import paths.

This issue should be opened again!

Also, I don't see why the proto files have `any|empty|timestamp/*` when the correct path is `google/protobuf`.

Please reopen this issue.

**Comment by fujita** [comment]
@gmelikov updated the doc. If it doesn't work for you, please update it.

**Comment by gmelikov** [comment]
@gustavooferreira yes, this patch helped me:
```
diff --git a/api/attribute.proto b/api/attribute.proto
index 4cf844f..7bf9452 100644
--- a/api/attribute.proto
+++ b/api/attribute.proto
@@ -21,7 +21,7 @@

 syntax = "proto3";

-import "any/any.proto";
+import "google/protobuf/any.proto";
 import "gobgp.proto";

 package gobgpapi;
diff --git a/api/gobgp.proto b/api/gobgp.proto
index b61b475..52dd9da 100644
--- a/api/gobgp.proto
+++ b/api/gobgp.proto
@@ -21,9 +21,9 @@

 syntax = "proto3";

-import "any/any.proto";
-import "empty/empty.proto";
-import "timestamp/timestamp.proto";
+import "google/protobuf/any.proto";
+import "google/protobuf/empty.proto";
+import "google/protobuf/timestamp.proto";

 package gobgpapi;


```

@fujita can you describe necessity of this change earlier in codebase? I didn't have enough time to dig in reasons, but if it's not only me here, let's discuss.

**Comment by gustavooferreira** [comment]
I haven't tested this in GO, but I don't see any reason why that patch wouldn't work with any language really, as this is the right way of importing the protobuf "well known types".

As it is, at the moment, it's really only a hack, where we provide the go path for ptypes folder with the -I flag and then do imports in this manner `any|empty|timestamp/*`, just because that's the way those files are laid down in the file system.

It messes up python imports and the only reason I see for this to not affect GO is because GO doesn't really depend on the files hierarchy for its modules/imports.

I hope you guys apply @gmelikov patch.

**Comment by gustavooferreira** [comment]
Also, your docs put emphasis on python being able to talk to gobgp (through gRPC).
It even has an example in the docs.

If you try to go through the example, it won't work.

So technically, the documentation doesn't really describe the process correctly.

What I'm trying to say is, this isn't just an extra thing that just so happens to not work. This is a primary use case in my opinion.

**Comment by gustavooferreira** [comment]
Had a quick look through the git history, this is the commit that made that change: 2965e809

Before that, the imports were correct.

**Comment by gmelikov** [comment]
@gustavooferreira easy :) I'm not an expert in Go, so I'd like to hear @fujita 's feedback and after that I'll be glad to make a PR.

**Comment by ecbaldwin** [comment]
This continues to be a stumbling block. The import paths are clearly incorrect. These are part of the google/protobuf package as documented [here][2]. This isn't a python issue; it is a protobuf issue. The correct way to import this is the following line as shown in the [protobuf documentation][1].

```
import "google/protobuf/any.proto";
```
Until this gets fixed, anyone trying to generate bindings for any language (except maybe Go, since it seems to do something special and probably incorrect) will have to change these to make them work. Please reopen this issue.

[1]: https://developers.google.com/protocol-buffers/docs/proto3#any
[2]: https://developers.google.com/protocol-buffers/docs/reference/google.protobuf
