### ISSUE TITLE
Performance evaluation with BGP Full Table

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#323]
Hello, folks!

We are interested in performance tests of GoBGP. So we could try to feed FullBGP to it and check how it going.

Do you have any benchmarks?

**Comment by tamihiro** [comment]
Pavel -

Let me chime in here although I'm pretty new to gobgp, because I've done a bit of testing lately.
My setup was to measure the time it would take for gobgpd to complete solely sending out all the update messages to its single peer.
```
AS65001: quagga bgpd
FreeBSD 7.2 on semi-junk PC
    |
AS65004: gobgpd
Ubuntu 14.04.2 on Xeon 3.07GHz x 2 (24 logical cores) + 64GB mem
    |
AS65001: Juniper MX5
running Junos 14.2R1.9
```
Routes are announced from top to bottom in the following way.
* Before gobgpd is started on 65004, full Internet BGP routes are already installed in quagga(65001), which also has peering to gobgpd configured with a neighbor shutdown statement, and peering to gobpgd is also activated on MX5(65001).
* Start gobgpd and subsequently disable peering with MX5.
* Hit *no shut* command on the quagga cli, and wait till gobgpd receives full routes from quagga.

Now all set, but before enabling the neighbor via gobgp cli, I start tcpdump on Ubuntu to monitor tcp 179 packets which will tell me how long it takes for it to update MX5 with full routes.

And here are the outcomes.

daemon tested on ubuntu server|time to complete|# of update msgs sent to MX5
----------------|--------|-----------
[1] gobgpd|02:34|551464
[2] gobgpd|02:06|203777
[3] gobgpd|01:08|89602
[4] quagga|01:14|89112

[1] First try dated 2015-08-26.
[2] Second try on the next day, with commits included up to 51494759aded7098e151869e66dd5b2c4d96ecfd.
[3] Next run on 2015-09-01, with commits included up to 70a8399e0dab0d9ee4c11959721e48e87ef261c0.
[4] For the comparision sake, Ubuntu package (0.99.22.4-3ubuntu1) of quagga's bgpd was tested on the same machine with the same senario.

Personally I have been very impressed with the above results, seeing how they have efficiated the way gobgpd handles multiple NLRIs of the idential attributes, and thus improved with the time it requires to send out full route updates.

**Comment by tamihiro** [comment]
Sorry I've just made a couple of corrections with my last comment as it incorrectly attributed mx5 to as65001 that was actually 65003. It can no way be the same asn as quagga on the top ^^;

**Comment by pavel-odintsov** [comment]
That's really nice! What about reproducible test case which I could run on my machine for performance evaluation?

**Comment by ishidawataru** [comment]
how about this?

https://github.com/osrg/bgperf

**Comment by pavel-odintsov** [comment]
Great great great! Brilliant! Thanks for this toolkit :)

**Comment by pjakma** [comment]
Note, if you're doing performance evaluations of convergence time of Quagga against GoBGP or BIRD, you should configure Quagga with a 0s MRAI ("neighbour ... advertisement-interval .."). Otherwise you're benching a BGP doing 0 buffering of updates against one deliberately holding on to routes to reduce churn and pack updates together for up to 5s (iBGP) or 30s (eBGP).

**Comment by pavel-odintsov** [comment]
We had many cases where GoBGP accidentally received full table and it was processed very well. I see no issues in such case. But it's pretty important to keep in mind that such case is not a best scenario for GoBGP.

**Comment by jauderho** [comment]
For reference, there is a recent comparison of different BGP implementations here: https://elegantnetwork.github.io/posts/comparing-open-source-bgp-stacks/
