### ISSUE TITLE
Ask for service name change for gRPC/protobuffers

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#332]
Hello!

I would like to ask to change standard name for protocol buffers from "api" namespace and "grpc" service name to something more uniq :) 

"grpc" and "api" names is very hard to understand because this class names used by gRPC itself or could be used by application authors. 

I could offer "Gobgp::GobgpClient" or we could remove package and sue GobgpClient only.

**Comment by ishidawataru** [comment]
Hi @pavel-odintsov,

Thanks for the suggestion.
I agree that current name "api" and "grpc" is not good.
However I think we need more appropriate name than you proposed.
Since we use the generated code also for the server(gobgpd), I want to avoid using "client".

I surveyed how protobuf package/server name is used in generated stub code.
```
package xxx
service YYY

## cpp
namespace xxx {
class YYY
}

## python
def early_adopter_create_YYY_server()
def early_adopter_create_YYY_stub()

xxx.Operation
xxx.Error
xxx.Arguments

## ruby
module Xxx
// doesn't use service name

## go
package xxx
type YYYClient interface {}
type YYYServer interface {}
```

From this survey, I propose "gobgpapi" for package name and "GobgpApi" for service name.
I admit it's not great name for cpp, but it works for all language I surveyed.

What do you think?

**Comment by pavel-odintsov** [comment]
I like this idea! You do nice investigation :)

**Comment by ishidawataru** [comment]
Done! https://github.com/osrg/gobgp/commit/e986668fc8de9b2e140601cbddc89a0c110cc269

**Comment by pavel-odintsov** [comment]
Awesome! I have ported my C++ library to new package and service names. So I have added support for multi-path announces. 

https://github.com/pavel-odintsov/gobgp_api_cpp_client/commit/a93cbcbba2131d17c2d3178a527952cb1f017a0b
