### ISSUE TITLE
High CPU utilization in Clos tree configuration

### ISSUE THREAD

**Issue by DanCripe** [osrg/gobgp#806]
I created a simulated Clos tree (4 spine, 4 leaf) using Docker containers. I initially validated using Quagga BGP, and then swapped in GoBGP. The gobgp daemons very quickly started using a significant amount of CPU in all containers. I verified that the daemons are continuously processing updates received from other gobgp daemons.

I believe this is due to the way gobgp calculates the best path. It currently does not bias toward selecting the same best path when sorting the available paths, so any of the equal cost paths may be selected, and this may change every time an update is processed. As a result, gobgpd may send an update to all peers every time it receives an update - and if the peers all do the same, updates are sent out exponentially. The code should bias toward selecting the previous best path (among equal cost candidates).

**Comment by fujita** [comment]
GoBGP uses Router-ID for best path selection so there are no equal cost paths if each peer has the unique Router-ID. GoBGP possibly sends lots of updates in such deployment because GoBGP sends updates immediately after receiving routes from other peers and calculating the best paths (no MRAI, the Minimum Route Advertisement Interval). IIUC, Quagga's default MRAI is 30 seconds for eBGP so you don't see so many updates. If you configure Quagga's MRAI to a smaller value, you would see the same issue.

The above describes the issue that you have?

**Comment by DanCripe** [comment]
The Router-ID path selection only applies to IBGP. See this code in compareByRouterID():

        // If both paths are from eBGP peers, then according to RFC we need
        // not tie break using router id.
        if !path1.IsIBGP() && !path2.IsIBGP() {
                return nil, nil
        }

As I'm using EBGP, there is no final selection, and the path selected is whichever path among the several lowest cost paths happens to be first in the list.

I've verified this with some experimental code (which is probably not the desired final code).

**Comment by fujita** [comment]
Can you try the latest?

**Comment by DanCripe** [comment]
Definitely fixed.
